project:
  type: website

website:
  title: "Sophie Hetche"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: myedu.qmd
        text: My Education
      - href: myfotos.qmd
        text: My Pictures
format:
  html:
    theme: lux
    css: styles.css
    toc: true
    




