---
title: "Curriculum Vitae"
about:
  template: marquee
  links:
    - icon: LinkedIn
      text: LinkedIn
      href: https://www.linkedin.com/in/sophie-hetche-728852234/
    - icon: github
      text: Github
      href: https://github.com/Soso-h
    - icon: Utrecht University
      text: email
      href: mailto:sophie.hetche@students.uu.nl
---

## Personal Profile
I am a curious and motivated master's student with a passion for learning, research, and practical problem-solving. Through my federal voluntary service and studies in psychology, I have developed valuable skills in communication, teamwork, and analytical thinking. My academic experiences have also taught me the importance of attention to detail and perseverance, which I enjoy applying to new challenges. I’m excited to apply this combination of skills and enthusiasm in dynamic and interdisciplinary environments, where I can contribute meaningfully to advancing knowledge and addressing real-world issues.

---

## Education

- **09/2023 – Current**: **Utrecht University**  
  M.Sc. Development and Socialization in Childhood and Adolescence | Current GPA: 8.5  

- **09/2020 – 07/2023**: **University of Twente**  
  B.Sc. Psychology (cum laude) | GPA: 8.75 | Bachelor thesis on community resilience and place attachment

- **09/2022 – 01/2021**: **University of Valencia**  
  Erasmus Semester Abroad | classes on delinquency, work psychology, psycholinguistics and emotional development 

- **2016 – 2019**: **Gymnasium Dionysianum in Rheine**  
  High School | Abitur (equivalent to A-level), final grade: 1,5  

- **2011 – 2016**: **Melanchthonschule Steinatal**  
  High School - until year 10  

---

## Projects

- **03/2023 – 07/2023**: **Contributing to Systematic Review on the Use of VR in Pain Management**  (publication in progress)
   | Reviewed and classified ~500 articles with a group of three other students and contributed significantly to writing the systematic review |

- **02/2022 – 07/2022**: **STAR Group Project on Moral Dilemmas in Daily Life**  
   | Planning and conducting focus group meetings with health care workers testing the use of a card game to stimulate moral decision making and empathy | Qualitative analysis |

- **04/2021 – 07/2021**: **STAR Group Project on Test Development**  
 | Confirmatory Factor Analysis | Classical Test Theory analyses | Item Response Theory analysis | Qualtrics and R Studio |

---

## Social Engagement

- **08/2019 – 07/2020: Federal Voluntary Social Service** at Christophorus-Schule in Rheine | Assisted disabled children (physically and mentally) through daily challenges while visiting school.

- **08/2018: Supervisor at the Szirmabesenyői Art-Camp** for children and young teenagers in Miskolc/Hungary on voluntary basis 


- **04/2017 – 04/2018: Denk Demokratie by Caritas e.V**  
  Explored the origins of democratic systems and their current development | Nationalism and Europeanism 

- **09/2016 – 01/2017: Diaconal Internship** at "Arbeitskreis Für Toleranz Und Menschenwürde"  
  supported refugees in writing letters, learning German, and cultural integration

---

## Additional Skills & Experiences

**Languages**  

- German (native), English (fluent), Spanish (A2)  

**Data Analysis Tools**  

- R Studio, SPSS, MPlus, HLM, JASP  

**Version Control & Tools**

- Proficient in Git and GitHub for basic skills including version control
- Experience using Quarto for creating dynamic, reproducible documents and websites

**Work**  

- Babysitting for international families (2018-current)  

---

## Contact
Feel free to reach out via LinkedIn or email for collaboration opportunities.
